### PR TITLE
appended RoboticsInfrastructure to paths

### PR DESCRIPTION
**Pull request by pawanw17**
#251

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
Paths are wrong since `git clone` puts files in `/opt/jderobot` without middle `RoboticsInfrastructure`.

```
Step 53/54 : RUN cp -r /opt/jderobot/RoboticsInfrastructure/CustomRobots/SelfDrivingModels /catkin_ws/src/SelfDrivingModels
 ---> Running in d0a186796913
cp: cannot stat '/opt/jderobot/RoboticsInfrastructure/CustomRobots/SelfDrivingModels': No such file or directory
The command '/bin/sh -c cp -r /opt/jderobot/RoboticsInfrastructure/CustomRobots/SelfDrivingModels /catkin_ws/src/SelfDrivingModels' returned a non-zero code: 1
```

Please test your changes before opening a PR

**Comment by pariaspe** [comment]
I'm closing this. The remaining changes are only related with wrong export paths in env file.

**Comment by pawanw17** [comment]
@pariaspe My bad I had cloned RoboticsInfrastructure in /opt/jderobot manually... which made RoboticsInfrastructure part of the path but the full command https://github.com/JdeRobot/RoboticsInfrastructure/blob/b92a5621f869c93203d3dff8f4e27f8ae7380d19/scripts/Dockerfile.pre-base#L302
removes it.

> Paths are wrong since `git clone` puts files in `/opt/jderobot` without middle `RoboticsInfrastructure`.
> 
> ```
> Step 53/54 : RUN cp -r /opt/jderobot/RoboticsInfrastructure/CustomRobots/SelfDrivingModels /catkin_ws/src/SelfDrivingModels
>  ---> Running in d0a186796913
> cp: cannot stat '/opt/jderobot/RoboticsInfrastructure/CustomRobots/SelfDrivingModels': No such file or directory
> The command '/bin/sh -c cp -r /opt/jderobot/RoboticsInfrastructure/CustomRobots/SelfDrivingModels /catkin_ws/src/SelfDrivingModels' returned a non-zero code: 1
> ```
> 
> Please test your changes before opening a PR

**Comment by pariaspe** [comment]
No problem, it is part of the reviewing process :+1:

**Pull request closed without merging**
