### PR TITLE
Removed unnecessary packages that are causing build failures

### PR DESCRIPTION
**Pull request by pawanw17**
Removed unnecessary packages from SelfDrivingModels. Fixes https://github.com/JdeRobot/RoboticsAcademy/issues/2006

These packages were causing catkin build failures

EDIT: Removing the packages has made RADI unstable, looking into it.

EDIT2: The instability was due to gazebo not finding models because I hadn't updated https://github.com/JdeRobot/RoboticsInfraestructure/blob/noetic-devel/scripts/.env to new model paths

### CODE REVIEW

**Comment by pawanw17** [comment]
I have tested it by 

1. Building the RADI
2. Launching the exercise
3. Running the exercise

https://github.com/JdeRobot/RoboticsInfraestructure/assets/40732709/ee9b189b-bdcf-4d94-a242-9ea6c901cad1

1. Is the SelfDrivingModels directory only used by Autoparkingv2?

2. To clean out the other packages that aren't needed
I suggest JDE Robot makes forks of these original Repos and I'll remove them with PRs
https://github.com/JdeRobot/RoboticsInfraestructure/blob/noetic-devel/scripts/.rosinstall

**Comment by pawanw17** [comment]
@pariaspe I have updated the video,

1) both versions of autoparking?

2) the repos listed in https://github.com/JdeRobot/RoboticsInfraestructure/blob/noetic-devel/scripts/.rosinstall
These are downloaded to catkin_ws to build

**Comment by pariaspe** [comment]
Thanks, it works now.

1. Only version 2, I believe that was the main improvement in these second version. When strongly tested, it will replace the old version
2. Yes, but I meant the original repo from the catvehicle was copied. Last two repos listed in .rosinstall will be removed soon

**Comment by pawanw17** [comment]
Since the SelfDrivingModels are only used in AutoparkingV2, this can be merged

**Review by pariaspe — APPROVED** [review]
Checked, it now builds successfully

**Pull request merged**
