### PR TITLE
Created a new follow_road world for Gz Harmonic

### PR DESCRIPTION
**Pull request by Arcane-01**
For issue #415 
Screenshot from 2024-07-08 05-54-37

### CODE REVIEW

**Review by pariaspe — CHANGES_REQUESTED** [review]
Awesome! What about having a circular road?

**Comment by Arcane-01** [comment]
Updated the world file
2024-07-09T03:03:46 887155159

**Comment by pariaspe** [comment]
@Arcane-01 World looks very cool, but I'm getting the following error:
```bash
$ gz sim follow_road.sdf
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
[Err] [SystemPaths.cc:525] Could not resolve file [osrf_first_office_diffuse.jpg]
[GUI] [Err] [SystemPaths.cc:525] Could not resolve file [osrf_first_office_diffuse.jpg]
```
Any clue why is not finding the jpg? World seems to load correctly

**Comment by Arcane-01** [comment]
Hi @pariaspe,
I was able to resolve that error by updating the image paths in the .dae file of the model.

**Review by pariaspe — APPROVED** [review]

**Comment by pariaspe** [comment]
Merged, I just changed tag world name value. It is important since gz world topics and services get that name. You can try a take a look with `gz service -l`.

**Pull request merged**
