### PR TITLE
Solves no module found error

### PR DESCRIPTION
**Pull request by pawanw17**
https://github.com/JdeRobot/RoboticsAcademy/issues/2253

### CODE REVIEW

**Comment by pawanw17** [comment]
Hi @pariaspe I am seeing this error while testing this,
```shell
root@ad47445dd995:/# ./entrypoint.sh 
Traceback (most recent call last):
  File "//RoboticsAcademy/src/manager/manager/manager.py", line 17, in <module>
    from src.manager.manager.launcher.launcher_engine import LauncherEngine
ModuleNotFoundError: No module named 'src'
root@ad47445dd995:/# BASE_DIR /RoboticsAcademy
BASE_DIR /RoboticsAcademy
./entrypoint.sh Watching for file changes with StatReloader
Performing system checks...

``` 
This disappears if I source .env in entrypoint.sh

**Comment by pariaspe** [comment]
Hi @pawanw17 , I've just tried again and it's working for me. How are you building the image? Does the dockerfile you are using have `ENV BASH_ENV /.env` somewhere?

**Comment by pawanw17** [comment]
Hi @pariaspe, I edited the dockerfile.mini_humble to point RoboticsInfrastructure to my fork and built  on latest local master (which had ENV BASH_ENV /.env) using 
`./build.sh -f --academy issue-2253 --infra pawan/RA-issue-2253 --ram main --ros humble --tag humble_1_oct_test`

but I am still seeing the same error
```shell
pawan@pawan-Legion:~/devel/RoboticsAcademy/scripts/mini_RADI$ docker run --rm -it -p 7164:7164 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 -p 7163:7163 jderobot/robotics-academy:humble_1_oct_test --debug
root@413a146ce7c8:/# ./entrypoint.sh 
Traceback (most recent call last):
  File "//RoboticsAcademy/src/manager/manager/manager.py", line 17, in <module>
    from src.manager.manager.launcher.launcher_engine import LauncherEngine
ModuleNotFoundError: No module named 'src'
root@413a146ce7c8:/# BASE_DIR /RoboticsAcademy
BASE_DIR /RoboticsAcademy
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 03, 2023 - 06:25:50
Django version 4.1.7, using settings 'academy.settings'
Starting development server at http://0.0.0.0:7164/
Quit the server with CONTROL-C.
root@413a146ce7c8:/# 

```

**Comment by pawanw17** [comment]
Hi @pariaspe , you are correct, I was building the image on master instead of issue-2253 branch, which didn't have `ENV BASH_ENV /.env`, I tested on the issue-2253 branch and it worked perfectly, so this MR is good to go, thanks!

**Pull request merged**
